import.js
=> resolves #15

lib/import_pipelines.js, package.json
=> migrate from FST to ngrams

.travis.yml, test/importPipeline.js
This also fixes the functional tests (pelias-model 1.0.0 made some changes), and updates the node versions from 0.10/0.11 to 0.10/0.12
=> Add functional tests to travis

test/importPipeline.js
pelias-model 1.1.0 now handles this itself
=> Remove phrase field handling

.travis.yml, package.json
Do all the things listed in pelias/pelias#258
Connects pelias/pelias#258
=> Improve travis

lib/importPipeline.js
With the latest version we can remove this hack!
Connects pelias/wof-admin-lookup#21
=> Let wof-admin-lookup handle stream end

package.json
connected to pelias/pelias#278
=> Rename address prop

lib/isValidCsvRecord.js, test/isValidCsvRecord.js
They snuck in there somehow. It happens.
=> Fix linter errors

README.md
The comment and the command weren't consistent.
=> Fix missing param in Readme

import.js
Testing semantic-versioning mostly
=> fix: whitespace

lib/streams/adminLookupStream.js, lib/streams/deduplicatorStream.js, test/streams/adminLookupStream.js, test/streams/deduplicatorStream.js
Added helper functions to simplify conditionals and make code more readable
=> Simplified conditionals

README.md, import.js
=> updated README to reflect current state

package.json
For some reason, github inexplicably closed #257
=> bumped wof-admin-lookup version, greenkeeper was acting weird

package.json
=> fix(package): update pelias-wof-admin-lookup to version 3.10.2

README.md
This is the start of some updates to the README we will want to make as part of https://github.com/pelias/pelias/issues/702.
Here there are some formatting updates and removal of the big section on the address deduplicator, which we would [like to deprecate](https://github.com/pelias/address-deduplicator/pull/22)
=> README formatting and content update

package.json
=> fix(package): update pelias-model to version 5.5.1

package.json
=> fix(package): update pelias-dbclient to version 2.5.4

package.json
=> fix(package): update combined-stream to version 1.0.7

utils/download_filtered.js
Today I made the silly mistake of not adding the `.csv` suffix to 'files' in my `pelias.json`.
The result was very noisy and appeared to be a download issue.
This PR adds an additional check to ensure the `files` array entries end with `.csv` before attempting a download.
=> ensure that sources end with ".csv"

package.json, test/data/expected.json
This should have been done as part of
https://github.com/pelias/model/pull/95
Looks like maybe greenkeeper missed it?
=> Upgrade to pelias/model-6.0.0

package.json, test/data/expected.json
This ensures all documents are indexed as the `doc` type, supporting ES6
Connects https://github.com/pelias/pelias/issues/719
=> feat(deps): Upgrade to pelias/model 7.0.0

lib/isValidCsvRecord.js, test/isValidCsvRecord.js
loosen detection of null island records to those in the general vicinity
fix for https://github.com/openaddresses/openaddresses/issues/5008
=> loosen detection of null island records to those in the general vicinity

package.json
```
npm i --save pelias-wof-admin-lookup
```
https://github.com/pelias/wof-admin-lookup/releases
=> upgrade deps

utils/download_all.js, utils/download_filtered.js
this PR is a proposed solution for https://github.com/pelias/docker/issues/267
closes https://github.com/pelias/docker/issues/267
=> download: improved error handling for cURL command

lib/streams/documentStream.js, test/streams/documentStream.js
@orangejulius as discussed yesterday, this is a basic implementation which would allow us to record G-NAF PIDs
=> addendum: add AU G-NAF PID values to addendum where available
