pelias/openaddresses

import.js, package.json
This can happen on import when the user is specifying a directory of
files and hasn't set anything else up in pelias.json
Thanks to @amiller2978 for originally reporting this
=> Handle case where entire openaddresses config is empty

lib/cleanup.js, lib/import_pipelines.js
This cleanup code handles numbered streets with leading zeros. For
example, `05th Street` will become `5th street`. This code only operates
on numbers with ordinal suffixes, so a street named `06 street` would
not be changed.
I tested the regex by running it across all of openaddresses and comparing the before and after street names. In total, there were 52239 entries that change, with 135 unique types of changes. I looked at all [135 changes](https://github.com/pelias/openaddresses/files/87825/unique-changes.txt) and they look right. There are 11 files affected by the change:
```
us/ca/los_angeles.csv
us/ca/san_diego.csv
us/ca/san_francisco.csv
us/co/clear_creek.csv
us/ne/cherry.csv
us/ne/dakota.csv
us/ne/gage.csv
us/nm/bernalillo.csv
us/pa/philadelphia.csv
us/wi/statewide.csv …
```
=> Add cleanup module with numbered street handling

lib/isValidCsvRecord.js, test/isValidCsvRecord.js
This protects the importer from files that are not at all valid OA data
files. That is, files with totally incorrect columns will essentially be
ignored, instead of causing the importer to crash.
Fixes #60
=> Check correct columns exist before checking length

bin/parallel, lib/parameters.js, package.json, test/parameters.js
This PR adds some parameters to the OA importer, as well as a bash script, to allow easily starting multiple OA importers that will run in parallel to import multiple files faster.
The importer now accepts two new command line parameters: `--parallel-count [integer]` and `--parallel-id [integer]`. If either of these aren't a valid number, nothing about the behavior of the importer will change.
If both ARE specified, then an additional step is added to the process of determining what CSV files to import. Normally, the importer is given either a list of files to import, or a directory, in which case it will find all CSV files in that directory and import each one sequentially. Either way, internally the importer is working through an array of files to import.
With both the above parameters …
=> Parallel imports

lib/importPipeline.js, lib/streams/isUSorCAHouseNumberZero.js, package.json, test/streams/isUSorCAHouseNumberZero.js, test/test.js
'0' house numbers are not legitimate in US/CA, so this PR removes them.  Filter must occur after admin lookup with it's based on `country_a` values.
Fixed #17
=> filter out '0' house numbers in US/CA

lib/isValidCsvRecord.js, test/isValidCsvRecord.js
Fixed pelias/pelias#127 (at least for OA)
Records are filtered out in the following conditions:
- `NUMBER` field value is literal word `NULL` (case insensitive)
- `STREET` field value contains literal word `NULL` on word boundary
- `STREET` field value is literal word `UNDEFINED` (case insensitive)
=> Filter out literal word `null` and `undefined`

lib/streams/isUSorCAHouseNumberZero.js, test/streams/isUSorCAHouseNumberZero.js
Previously, only literal `0` house numbers were filtered out in USA/CAN.  There are presently ~67k US/CA OA records with house numbers reduceable to `0` above and beyond literal `0`.  This removes them.
Fixed #106
=> filter out records w/house number reduceable to 0

.travis.yml
We are beginning to officially depricate it.
=> Remove Node 0.10 from Travis versions

lib/importPipeline.js
These snuck in somehow. Should we change the maximum number of parameters a function can have before jshint complains? It's currently set to 5. Alternatively we could try to refactor to require fewer parameters.
=> Fix linter errors

lib/cleanup.js, test/streams/cleanupStream.js
=> Removing the extra white space from the middle of street names

bin/parallel
This small change helps us keep all knowledge of how to run the importer
in one place.
=> Use NPM start in parallel script

lib/cleanup.js, test/data/expected.json, test/streams/cleanupStream.js, test/streams/recordStream.js
Attempts to standardize capitalization in street names such that each word begins with a capital.
Fixes #95
=> Fix capitalization

README.md, import.js, lib/parameters.js, lib/streams/adminLookupStream.js, lib/streams/deduplicatorStream.js, package.json, test/parameters.js, test/streams/adminLookupStream.js, test/streams/deduplicatorStream.js, test/test.js
This should allow the openaddresses importer to, instead of accepting command line arguments, to enable (and disable) admin lookup and deduplication via the config.
Connects pelias/pelias#255
Fixes #51
=> Config imports

lib/streams/documentStream.js
_I found this cleaning out some code sitting on my machine_
This is no longer needed now that we fully trim whitespace in the name
field in [cleanupStream.js](https://github.com/pelias/openaddresses/blob/master/lib/streams/cleanupStream.js#L16-L20).
=> Remove trimming regex

.jshintrc, lib/streams/documentStream.js, test/streams/documentStream.js
The OA hash is calculated from the data in each row, so rows with
identical data have identical hashes. This is nice for two reasons:
1.) It means bit-for-bit duplicate records will no longer be inserted
into Elasticsearch multiple times. Instead one document will be updated
several times. This is not quite as efficient as, and is no substitute
for, actually removing duplicate lines from OA files before importing as
a preprocessing step, but it's still nice.
2.) Our current ID scheme simply uses a counter starting at zero, so you
can only find the record if you're sure you have the same file, and want
to count line numbers. The hash will be the same, assuming the data is
the same, even if the file being looked at is newer or older than the
one that was used to import.
**Bonus**
This PR …
=> Use OA hash field instead of 

lib/parameters.js, test/parameters.js
There were no tests for when config had no data files specified and should glob them all.  Simplified logic with lodash, as well.
=> Cleanup data file globbing

configValidation.js, package.json, test/configValidation.js
`validate` was being called with the root whereas the function itself was working off of the `imports.openaddresses` element.
=> validate config starting at root element, not subelement

lib/isValidCsvRecord.js, test/isValidCsvRecord.js
Fixes #276 and therefore mapzen/leaflet-geocoder#163
=> filter out records with lat/lon both parseable as 0

.travis.yml
Greenkeeper now requires Node.js version 8. Fortunately, `npx` easily lets
us run just Greenkeeper with that Node version.
=> Use NPX to run Greenkeeper with Node.js 8

lib/streams/cleanupStream.js
This line was causing many thousands of log entries to be printed during every import.
=> Remove very verbose importer log

utils/download_all.js
Previously, we would download only the freely distributable OA data,
which is the majority.
It's useful to have all the OA data though.
=> Download share-alike OA data

lib/cleanup.js, test/streams/cleanupStream.js
Ensuring proper capitalization has been a challenge for the OA importer for a long time. We made some initial efforts in https://github.com/pelias/openaddresses/pull/131.
This PR expands on the framework that work set up, and ensures street directionals (NW, SW, NE, SE) are always capitalized.
To do some testing, I've created a debug branch of the OA importer that writes just the name field to a file, instead of importing to Elasticsearch. A normal import takes about 2 days, but this branch can process the entire OA dataset in about 10 hours. Using that, we can take a look at the resulting diff output and see if there are any unexpected impacts of this change.
I would love to know if there are common words or abbreviations in any languages that would conflict with this change, but based …
=> Fully capitalize street directional abbreviations

test/importPipeline.js, utils/download_filtered.js
When downloading OA data, each file is written to a temporary file with a completely random name. This makes debugging failed downloads difficult.
This PR changes the filename to include the OA source, so bad files can be tracked down.
=> Show filename of OA download

bin/units, package.json
The way we were running our unit tests does not catch fatal errors in the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail` option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744
=> feat(test): Use dedicated test script to catch errors

bin/parallel, bin/start
The parallel import functionality requires parameters to be passed. The start script was not doing this.
=> fix(parallel-import): pass all parameters in start script

README.md, lib/streams/recordStream.js, schema.js
This adds a config option similar to the one in the [Who's on First importer](https://github.com/pelias/whosonfirst#configuration), which will allow users of this importer to decide if a missing file should count as a fatal error or be skipped gracefully.
Previously, this importer would import files until it got to one that doesn't exist, and then exit with an unclear error.
Now, the importer either quits right away (if `missingFilesAreFatal` is true), or emits a warning message and continues with the other files. Gracefully skipping missing files is now the default.
Fixes https://github.com/pelias/openaddresses/issues/311
=> feat(import): add missingFilesAreFatal option

bin/parallel
This allows the ./bin/parallel script to handle the case where no, or incorrect, parallelization argument is passed.
With this change, it's safe to use essentially as a substitute for ./bin/start
=> feat(parallel): improve paralell script

import.js, lib/importPipeline.js, package.json, test/importPipeline.js
This allows distinguishing which logger output lines correspond to which
importer during an import.
Unlike other importers, this PR is slightly more complicated as we have
to support unique names for each of what might be several parallel
sub-importers.
Dependency injection for `dbclient` was removed in favor of using
`proxyquire` for testing to facilitate this.
Connects pelias/dbclient#101
=> Use new dbclient name functionality

utils/download_filtered.js
The OpenAddresses download did not include error handling that took the `missingFilesAreFatal` parameter into account. Therefore, all download errors stopped the entire download process.
Especially for large areas that include many of the individual OA files, gracefully skipping files that have download errors can be a convenient way to handle sources that are having issues.
Fixes https://github.com/pelias/openaddresses/issues/425
=> fix(download): Respect `missingFilesAreFatal` parameter

utils/download_filtered.js
This was broken inadvertently in https://github.com/pelias/openaddresses/pull/428
=> fix(download): Fix incorrect download error handling

utils/download_all.js
The OA project can incur significant costs when many users download directly from S3.
This PR changes the URL used for 'global' downloads to point to their Cloudflare CDN.
=> download openaddresses "global" files via cloudflare CDN

package.json, utils/download_filtered.js
Replaces #434, to fix #433.
Implements:
- limit the rate of HTTP requests to OpenAddresses to 10 per minute. See https://github.com/pelias/openaddresses/issues/433#issuecomment-527383976
- interruption on Ctrl+C
=> Rate limiting, using bottleneck

README.md, schema.js, utils/download_all.js
This allows specifying a custom location to download OpenAddresses data from, which can be useful for a variety of reasons.
cc @Joxit :)
=> Allow configuring download location

lib/streams/contentHashStream.js, lib/streams/recordStream.js, test/data/expected.json, test/streams/contentHashStream.js, test/test.js
Following on from a discussion with the OA team, we will begin generating our own content hashes for each row of the CSV file.
The original intention of the `HASH` field was to provide a semi-stable identifier for each row in order to:
- provide an addressable identifier for each row
- facilitate deduplication between imports (such as duplicates in the `us/or/portland_metro` and `us/or/portland` files).
- allow for blacklisting of records using their GID
It turns out that the existing `HASH` column generated by the OA team is [seeded with a random number](https://github.com/openaddresses/machine/blob/b08a622669af7d896739f87891c13ca8b527b5b9/openaddr/conform.py#L1003), so even if the underlying data remains the same, the hash value will change with each rebuild of the OA file.
eg:
```bash …
```
=> generate semi-permanent content hashes for OA rows

utils/download_all.js, utils/download_filtered.js
On versions of Node older than 12.x, the maxBuffer size is significantly smaller.  While I was trying to run the openaddresses downloader, I noticed that my downloads kept failing because the buffer was filling up.  
This was caused by the progress output being sent to stdout/stderr from curl.  This PR just changes the curl command to run silently to avoid ever filling up the buffer causing your download to fail.
=> Run curl silently to avoid using up all of the stdout/stderr buffer.

package.json, test/data/expected.json
As of `pelias-config@4.8.0`, the default Elasticsearch type name is now `_doc`, which is the value compatible with Elasticsearch 7.
This PR updates the functional tests to expect that new value and ensures that the appropriate version of `pelias-config` is used going forward.
Connects https://github.com/pelias/config/pull/122
Connects https://github.com/pelias/pelias/issues/831
Fixes https://github.com/pelias/openaddresses/issues/450
=> Update test expectations for new doc type name

package.json, test/importPipeline.js, test/streams/cleanupStream.js, test/streams/contentHashStream.js, test/streams/documentStream.js, test/streams/germanicAbbreviationStream.js, test/streams/isUSorCAHouseNumberZero.js
closes https://github.com/pelias/openaddresses/pull/429 as replacement
I pulled the code from `benetis` and cleaned up the tests as per `orangejulius` comments so we can merge this.
Also rebased `master` and fixed one tests. that came in since the original PR.
=> move away from event-stream, replace with stream-mock

lib/streams/recordStream.js
This log has always been a pain. It's on a simple 10 second timer so it will print forever, even if nothing has changed.
It's measuring the number of records that were invalid, which is not a particularly notable thing. There are invalid records in OA data all the time.
Overall, we don't really need this and it's just cluttering up other, more important, log output.
=> feat(logs): Remove bad record count verbose logger

package.json
We want to ensure the fix for https://github.com/pelias/wof-admin-lookup/issues/288, contained in https://github.com/pelias/wof-admin-lookup/pull/297, is used when importing.
=> fix(deps): Upgrade wof-admin-lookup to the latest

package.json
Reverts pelias/openaddresses#466
Unfortunately I have to revert this change because the authors of `npm tmp` don't adhere to the semantic versioning spec and have recently been publishing a bunch of breaking changes under the minor versions `0.2.x` 😢 
More specifically, the following change was introduced in a minor version which broke our download script:
```bash
> require('tmp').tmpNameSync({prefix: 'foo', dir: '/code', postfix: '.zip'})
'/code/foo16hKdNdr67yY0D.zip'
> require('tmp').tmpNameSync({prefix: 'foo', dir: '/code', postfix: '.zip'})
Thrown:
Error: dir option must be relative to "/tmp", found "/code".
at _assertIsRelative (/code/pelias/openaddresses/node_modules/tmp/lib/tmp.js:599:13)
at _assertAndSanitizeOptions (/code/pelias/openaddresses/node_modules/tmp/lib/tmp.js:513:5)
at …
```
=> Revert "Update tmp to the latest version 🚀"

package.json, utils/download_all.js, utils/download_filtered.js
use npm "temp" instead of npm "tmp".
It doesn't make much sense to have both modules when `temp` can do everything `tmp` does 🤷 
The documentation for `temp` isn't super clear on the usage of `.path()` (edit: [this is the relevant part](https://github.com/bruce/node-temp#affixes)), it's a bit clearer by [looking at the code](https://github.com/bruce/node-temp/blob/master/lib/temp.js#L43-L73).
This code isn't covered by unit tests so this PR is DRAFT until I can figure out how to manually test it.
=> use npm "temp" instead of npm "tmp"

Dockerfile, README.md, schema.js, utils/download_all.js
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
Downloading from `https://data.openaddresses.io` is extremely slow, as they are throttling all downloads.
I could not find any mirror out there and the only solution to fast download I found was S3, with the [requester pays](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html) option.
---
I added an option to allow downloading the oa files from S3, with the possibility to add options like `--request-payer`. This speeds up the download extremely, with the only inconvenient that you'll have to pay for the data transfer.
---
Use the following options in `pelias.json`
```json
"openaddresses": {
"dataHost": "s3://data.openaddresses.io", …
```
=> Allow download from s3

lib/isValidCsvRecord.js, lib/parameters.js, lib/streams/recordStream.js, package.json
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
I wanted to retrieve fresh data from OpenAddresses and saw that they had completely changed their data format. The data is now available on [batch.openaddresses.io](https://batch.openaddresses.io/data) and they serve ndjson instead of csv. 
---
I've updated the importer to support both csv and geojson files at import time.
=> Add support for OpenAddresses geojson format

utils/download_all.js, utils/download_filtered.js
As discussed in https://github.com/pelias/openaddresses/issues/482 this PR adds a referer header to cURL requests sent to download data from `results.openaddresses.io`.
requires confirmation that it works as expected before merging.
closes https://github.com/pelias/openaddresses/issues/482
=> add referer header to cURL requests

utils/download_all.js
As per discussion in https://github.com/pelias/openaddresses/issues/484 this PR changes the "collected" OA downloads (ie. `openaddr-collected-global.zip` and `openaddr-collected-global-sa.zip`) to run in *series* rather than in *parallel*.
The reason for this change is that the OA CDN has a "Maximum Connections Per IP" limit of 1.
Prior to this PR, cURL would *intermittently* receive an HTML file containing the text `503 Service Unavailable`, when `unzip` attempted to open this file it would error the cryptic message `End-of-central-directory signature not found`.
The positive effect of this PR is that the downloads will no longer only succeed *intermittently*, the negative effect is that downloads will be slower since the second file isn't started until the first has complete.
I noticed …
=> download: cURL "collected" files in series

lib/analysis/dictionaries/en/diagonal_contractions.txt, lib/cleanup_v2.js, test/cleanup_v2.js
as a follow on from https://github.com/pelias/openaddresses/pull/477 and pairing with https://github.com/pelias/openstreetmap/pull/560 this PR contracts English diagonals in street names.
it only targets four terms `["southeast", "southwest", "northeast", "northwest"`], when those tokens are found they are replaced with the contracted form `[SE, SW, NE, NW]`.
as such it's pretty safe
=> street_name_normalization: contract english diagonals

utils/download_all.js
as discussed in https://github.com/pelias/docker/issues/266 the `aws s3 cp` command outputs regular progress information to `stdout`.
since we're using `child_process.exec` the `stdout` is buffered until the process exits, if the buffer (1MB by default) fills up then an error occurs.
we're not using the return value of `child_process.exec` (from what I could tell), so adding [--only-show-errors](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) suppresses it, while also not having to worry about conflicting/duplicate `--no-progress` flags provided by the user.
if we would like to return regular status reports of the file as it downloads then we would need to change `child_process.exec` to `child_process.spawn` and refactor accordingly, the latter allows customisation of the …
=> download: suppress progress indicator for aws s3 cp command

lib/streams/recordStream.js, package.json
same as https://github.com/pelias/csv-importer/pull/93 (including npm version bump)
resolves https://github.com/pelias/openaddresses/issues/494
=> strip byte-order-mark from CSV files

package.json, test/data/expected.json, test/importPipeline.js
this PR upgrades `pelias/model` to the latest version.
looking through [the changelog](https://github.com/pelias/model/releases) there is nothing which will effect the OA importer, which is probably why we didn't do this sooner.
=> upgrade pelias-model to latest version

lib/streams/unitSplittingMapperStream.js, test/data/expected.json, test/streams/unitSplittingMapperStream.js
this PR implements https://github.com/pelias/openaddresses/issues/503
=> unit-number-extractor: remove unit number from name.default

lib/streams/gnafMapperStream.js, test/streams/gnafMapperStream.js
as reported in Gitter, a warning is emitted when the source data doesn't have a valid `ID` column.
I thought this was impossible, apparently not.
good news is it's only a warning and the rest of the importer will continue as expected, this PR silences it.
=> gnaf: silence gnaf mapper warning when ID field is undefined

lib/analysis/Token.js, lib/analysis/ordinals.js, lib/cleanup_v2.js, test/cleanup_v2.js
following on from https://github.com/pelias/openaddresses/pull/477 et al, this is something we were missing which annoyed me.
it was a relatively simple task to add missing street ordinals to numeric street names.
=> analysis: append ordinal suffix to numeric street names

package.json
The package `split2` is present in both `dependencies` and `devDependencies`.
This causes an `MODULE_NOT_FOUND` error when we install the project with `npm install --omit=dev`
```
node:internal/modules/cjs/loader:998
throw err;
^
Error: Cannot find module 'split2'
Require stack:
- /opt/pelias/lib/streams/recordStream.js
- /opt/pelias/lib/importPipeline.js
- /opt/pelias/import.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
at Function.Module._load (node:internal/modules/cjs/loader:841:27)
at Module.require (node:internal/modules/cjs/loader:1067:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/opt/pelias/lib/streams/recordStream.js:7:15)
at Module._compile (node:internal/modules/cjs/loader:1165:14)
at …
```
=> fix: remove split2 from `devDependencies`

lib/parameters.js, lib/streams/recordStream.js
Hi there, I added a new feature for OpenAddresses importer.
OA now uses the GeoJSON format which is very verbose and therefore much heavier than CSV. It is increasingly complicated to manage the disk space that can be optimized.
So, for space efficiency I thought it would be nice to store only gzip versions on disk and import them. This may use more CPU but it will be the user's choice.
With this PR we are now able to import both raw and gzipped CSV and GeoJSON.
Example for French countrywide addresses from latest build and 2020 CSV build.
| File | Number of entries | Raw Size | Gzip Size | 
| --- | ---: | ---: | ---: | 
| fr/countrywide-addresses-country.geojson | 26M | 6.6G | 688M |
| fr/countrywide.csv | 25M | 2.4G | 584M |
=> Add support to *.gz data at import

Dockerfile
This removes the `unzip` package from the Docker image. It's already baked into our Pelias baseimage, so this change should have no impact.
=> Docker: Remove unused dependency
